project:
  type: website

website:
  title: "ExceLovers"
  navbar:
    right:
      - proposito.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/charlie-arturo-do-amaral-becerra/
 

format:
  html:
    theme: cosmo
    css: styles.css



